name: flutter_pkg_lockated_book_parking
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_pkg_resident_urbanwork_widgets:
    path: ../flutter_pkg_resident_urbanwork_widgets

  flutter_pkg_lockated_gophygital_widgets:
    path: ../flutter_pkg_lockated_gophygital_widgets

  http: ^1.1.0
  json_annotation: ^4.4.0
  provider: ^6.1.2
  firebase_analytics:   ">=11.4.0 <13.0.0"
  logger: ^2.0.2
  shared_preferences: ^2.2.2
  google_fonts: ^6.3.2 
  syncfusion_flutter_sliders: ^29.1.39
  syncfusion_flutter_core: ^29.1.39 
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dotted_decoration: ^2.0.0
  table_calendar: ^3.0.3  
  clippy_flutter: ^2.0.0-nullsafety.1
  flutter_secure_storage: ^10.0.0-beta.4
  geolocator: ^10.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/transport/
    - assets/images/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package





# name: flutter_pkg_lockated_book_parking
# description: "A new Flutter package project."
# version: 0.0.1
# homepage:

# environment:
#   sdk: ^3.7.2
#   flutter: ">=1.17.0"

# dependencies:
#   flutter:
#     sdk: flutter

#   flutter_pkg_resident_urbanwork_widgets:
#     path: ../flutter_pkg_resident_urbanwork_widgets

#   flutter_pkg_lockated_gophygital_widgets:
#     path: ../flutter_pkg_lockated_gophygital_widgets

#   http: ^1.1.0
#   json_annotation: ^4.4.0
#   provider: ^6.1.2
#   firebase_analytics: ">=11.4.0 <13.0"
#   logger: ^2.0.2
#   shared_preferences: ^2.2.2
#   google_fonts: ^6.3.2 
#   syncfusion_flutter_sliders: ^29.1.39

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^5.0.0

# # For information on t he generic Dart part of this file, see the
# # following page: https://dart.dev/tools/pub/pubspec

# # The following section is specific to Flutter packages.
# flutter:

#   # To add assets to your package, add an assets section, like this:
#   # assets:
#   #   - images/a_dot_burr.jpeg
#   #   - images/a_dot_ham.jpeg
#   #
#   # For details regarding assets in packages, see
#   # https://flutter.dev/to/asset-from-package
#   #
#   # An image asset can refer to one or more resolution-specific "variants", see
#   # https://flutter.dev/to/resolution-aware-images

#   # To add custom fonts to your package, add a fonts section here,
#   # in this "flutter" section. Each entry in this list should have a
#   # "family" key with the font family name, and a "fonts" key with a
#   # list giving the asset and other descriptors for the font. For
#   # example:
#   # fonts:
#   #   - family: Schyler
#   #     fonts:
#   #       - asset: fonts/Schyler-Regular.ttf
#   #       - asset: fonts/Schyler-Italic.ttf
#   #         style: italic
#   #   - family: Trajan Pro
#   #     fonts:
#   #       - asset: fonts/TrajanPro.ttf
#   #       - asset: fonts/TrajanPro_Bold.ttf
#   #         weight: 700
#   #
#   # For details regarding fonts in packages, see
#   # https://flutter.dev/to/font-from-package
